// A77 sound design v1: a tiny WebAudio CHIPTUNE synth — every cue is generated
// at runtime from oscillators + gain envelopes, so there are ZERO audio assets
// and zero licensing surface (original/generated by construction, and the
// square/triangle timbres are period-correct for a 1991 homage). It subscribes
// to session.onChange, maps each fog-filtered event to a cue via sound-map.js,
// and plays it through a master→effects gain honoring the ⚙ split (master +
// effects + music, SEPARATE from reduceAnimation, which never mutes). Two short
// procedural TUNES (creation + splash) loop on the same synth; the full
// soundtrack is later by design. QUALITY is a human listening pass (the user's
// ears) — this file's bar is: builds without throwing, cues fire on the right
// events, sensible defaults.
import { soundForEvent } from './sound-map.js';
import { filterEvents } from '../../engine/visibility.js';

// equal-tempered note frequencies (Hz), A4=440
const NOTE = {
  C3: 130.81, E3: 164.81, G3: 196.00, A3: 220.00,
  C4: 261.63, D4: 293.66, E4: 329.63, F4: 349.23, G4: 392.00, A4: 440.00, B4: 493.88,
  C5: 523.25, D5: 587.33, E5: 659.25, G5: 783.99, C6: 1046.50
};

// A cue recipe: a sequence of notes (freq, delay from cue start, duration),
// each an oscillator of `wave` through a short attack/decay envelope at `gain`.
// Helpers build the common shapes so the table stays readable.
function seq(wave, gain, notes) { return { wave, gain, notes }; }
function chord(wave, gain, freqs, dur) { return seq(wave, gain, freqs.map(f => [f, 0, dur])); }
function arp(wave, gain, freqs, step, dur) { return seq(wave, gain, freqs.map((f, i) => [f, i * step, dur])); }
function fall(wave, gain, from, to, dur) { return seq(wave, gain, [[from, 0, dur * 0.5], [to, dur * 0.5, dur * 0.5]]); }

const RECIPES = {
  'combat-win': seq('square', 0.2, [[NOTE.C4, 0, 0.1], [NOTE.E4, 0.09, 0.1], [NOTE.G4, 0.18, 0.1], [NOTE.C5, 0.27, 0.34]]), // user: longer + more triumphant — a rising fanfare held on the high C
  'combat-loss': fall('sawtooth', 0.16, NOTE.E4, NOTE.C4, 0.22),                    // a sad drop
  'combat-distant': seq('triangle', 0.05, [[NOTE.C4, 0, 0.06]]),                    // a faint clash
  'capture-win': seq('square', 0.2, [[NOTE.G4, 0, 0.1], [NOTE.C5, 0.09, 0.1], [NOTE.E5, 0.18, 0.1], [NOTE.G5, 0.27, 0.36]]), // user: more triumphant — a brighter, higher rising fanfare
  'capture-loss': fall('sawtooth', 0.18, NOTE.C4, NOTE.G3, 0.3),
  'capture-distant': seq('triangle', 0.05, [[NOTE.G3, 0, 0.08]]),
  'found': arp('triangle', 0.16, [NOTE.C4, NOTE.G4], 0.07, 0.14),                   // a settling chime
  'grow': seq('triangle', 0.13, [[NOTE.G4, 0, 0.08], [NOTE.C5, 0.06, 0.1]]),
  'starve': fall('sine', 0.14, NOTE.A3, NOTE.E3, 0.28),
  'build': seq('square', 0.14, [[NOTE.C4, 0, 0.09], [NOTE.E4, 0.08, 0.09], [NOTE.G4, 0.16, 0.22]]), // user: more triumphant — a confident rising C-E-G held on G
  'disorder': seq('sawtooth', 0.11, [[NOTE.C3, 0, 0.26], [NOTE.C3 * 1.06, 0.03, 0.26], [NOTE.E3, 0.07, 0.24], [NOTE.C3 * 0.94, 0.12, 0.28]]), // user: a RIOT of unhappy people — a detuned low cluster that beats/murmurs like an angry crowd
  'order': arp('triangle', 0.12, [NOTE.E4, NOTE.G4, NOTE.C5], 0.05, 0.1),
  'tech': arp('square', 0.12, [NOTE.G4, NOTE.C5, NOTE.E5, NOTE.G5], 0.045, 0.09),   // a sparkle
  'wonder': arp('square', 0.2, [NOTE.C4, NOTE.E4, NOTE.G4, NOTE.C5, NOTE.E5], 0.08, 0.2), // fanfare
  'age': arp('square', 0.22, [NOTE.C4, NOTE.G4, NOTE.C5, NOTE.E5, NOTE.G5, NOTE.C6], 0.09, 0.26), // the historian's fanfare
  'defeat': fall('sawtooth', 0.2, NOTE.A3, NOTE.C3, 0.5),
  'elimination': seq('triangle', 0.14, [[NOTE.E4, 0, 0.24], [NOTE.C4, 0.22, 0.24], [NOTE.A3, 0.44, 0.28], [NOTE.E3, 0.66, 0.44]]), // user: longer + sadder — a slow descending minor line settling on a held low E
  'barbarian': seq('sawtooth', 0.16, [[NOTE.C3, 0, 0.14], [NOTE.E3, 0.07, 0.14]]),  // a menacing horn
  'victory': arp('square', 0.24, [NOTE.C4, NOTE.E4, NOTE.G4, NOTE.C5, NOTE.G4, NOTE.C5], 0.1, 0.28),
  'gameover': fall('sawtooth', 0.2, NOTE.G3, NOTE.C3, 0.6),
  'government': arp('triangle', 0.14, [NOTE.C4, NOTE.F4, NOTE.A4], 0.07, 0.14),
  'regent': seq('square', 0.11, [[NOTE.C4, 0, 0.08], [NOTE.G4, 0.08, 0.14]]),       // user: a "yes, sir" — a crisp two-note affirmative rising a confident fifth
  // A76 space race (H8 presentation pass)
  'ship-part': seq('square', 0.13, [[NOTE.E4, 0, 0.06], [NOTE.A4, 0.05, 0.11]]),    // an assembly clink — two quick rising taps, metal on metal
  // XIV §26: era-specific tech-discovery fanfares (~2 s, held open by the
  // celebration overlay — not auto-dismissed). Four characters per the ally
  // design; reviewable/tunable in debugging/soundboard.html.
  'discovery-ancient': seq('sawtooth', 0.16, [[NOTE.C3, 0, 0.4], [NOTE.G3, 0.34, 0.4], [NOTE.C4, 0.68, 0.5], [NOTE.E4, 1.1, 0.8]]),      // struck bronze / low reed
  'discovery-classical': seq('triangle', 0.16, [[NOTE.C5, 0, 0.55], [NOTE.E5, 0.3, 0.55], [NOTE.G5, 0.6, 0.5], [NOTE.C6, 0.95, 0.9]]),   // bell-like / strings
  'discovery-industrial': seq('square', 0.15, [[NOTE.C4, 0, 0.24], [NOTE.C4, 0.3, 0.24], [NOTE.G4, 0.6, 0.3], [NOTE.C5, 0.98, 0.7]]),    // measured brass / mechanical rhythm
  'discovery-modern': seq('sawtooth', 0.13, [[NOTE.C4, 0, 0.4], [NOTE.G4, 0.3, 0.4], [NOTE.C5, 0.6, 0.4], [NOTE.E5, 0.9, 0.4], [NOTE.G5, 1.2, 0.9]]), // rising electronic sweep
  'ship-launch': arp('sawtooth', 0.18, [NOTE.C3, NOTE.G3, NOTE.C4, NOTE.E4, NOTE.G4, NOTE.C5, NOTE.E5], 0.09, 0.2), // a long climb from rumble to bright — the ascent itself
  'ship-down': seq('sawtooth', 0.17, [[NOTE.E4, 0, 0.16], [NOTE.C4, 0.14, 0.18], [NOTE.G3 * 0.94, 0.3, 0.4]])       // a breaking fall ending detuned — something came apart
};

// The two TUNES: short looping note lists [freq, dur] on a mellow triangle.
const TUNES = {
  creation: { wave: 'triangle', gain: 0.09, tempo: 0.34, notes: [
    NOTE.C4, NOTE.E4, NOTE.G4, NOTE.E4, NOTE.A4, NOTE.G4, NOTE.E4, NOTE.C4,
    NOTE.D4, NOTE.F4, NOTE.A4, NOTE.F4, NOTE.G4, NOTE.E4, NOTE.D4, NOTE.C4] },
  splash: { wave: 'triangle', gain: 0.08, tempo: 0.42, notes: [
    NOTE.C4, NOTE.G4, NOTE.E4, NOTE.G4, NOTE.F4, NOTE.A4, NOTE.G4, NOTE.E4,
    NOTE.D4, NOTE.G4, NOTE.C5, NOTE.G4, NOTE.E4, NOTE.G4, NOTE.C4, NOTE.C4] }
};

export function initSound(ctx) {
  const opt = ctx.options;
  let actx = null;      // created lazily (autoplay policy: needs a user gesture)
  let masterGain = null;
  let tuneTimer = null;
  let played = 0;       // cue counter (test hook)

  function ensureContext() {
    if (actx) { if (actx.state === 'suspended') actx.resume(); return actx; }
    const AC = window.AudioContext || window.webkitAudioContext;
    if (!AC) return null;
    actx = new AC();
    masterGain = actx.createGain();
    masterGain.connect(actx.destination);
    return actx;
  }
  // resume the context on the first user gesture (browsers block audio before it)
  const resume = () => { if (actx && actx.state === 'suspended') actx.resume(); };
  window.addEventListener('pointerdown', resume);
  window.addEventListener('keydown', resume);

  function vol(kind) {
    const master = num(opt ? opt.get('soundMaster') : 70, 70) / 100;
    if (kind === 'fx' && opt && opt.get('soundEffects') === false) return 0;
    if (kind === 'music' && opt && opt.get('soundMusic') === false) return 0;
    return master;
  }
  function num(v, d) { const n = parseInt(v, 10); return Number.isFinite(n) ? n : d; }

  // schedule one recipe's notes as enveloped oscillators
  function render(recipe, kind, tuneGain) {
    const c = ensureContext();
    if (!c || masterGain === null) return;
    const g = vol(kind) * (tuneGain !== undefined ? 1 : 1);
    if (g <= 0) return;
    const now = c.currentTime;
    for (const [freq, delay, dur] of recipe.notes) {
      const osc = c.createOscillator();
      const env = c.createGain();
      osc.type = recipe.wave;
      osc.frequency.value = freq;
      const t0 = now + delay;
      const peak = recipe.gain * g * (tuneGain === undefined ? 1 : tuneGain);
      env.gain.setValueAtTime(0.0001, t0);
      env.gain.exponentialRampToValueAtTime(Math.max(peak, 0.0002), t0 + 0.008); // fast attack
      env.gain.exponentialRampToValueAtTime(0.0001, t0 + dur);                    // decay
      osc.connect(env); env.connect(masterGain);
      osc.start(t0); osc.stop(t0 + dur + 0.02);
    }
  }

  function play(id) {
    const recipe = RECIPES[id];
    if (!recipe) return;
    render(recipe, 'fx');
    played += 1;
  }

  // --- music: loop a tune until stopped -------------------------------------
  function playTune(name) {
    const tune = TUNES[name];
    if (!tune) return;
    stopTune();
    let i = 0;
    const stepMs = tune.tempo * 1000;
    const tick = () => {
      if (vol('music') > 0) render({ wave: tune.wave, gain: tune.gain, notes: [[tune.notes[i], 0, tune.tempo * 0.9]] }, 'music', 1);
      i = (i + 1) % tune.notes.length;
    };
    tick();
    tuneTimer = setInterval(tick, stepMs);
  }
  function stopTune() { if (tuneTimer) { clearInterval(tuneTimer); tuneTimer = null; } }

  // XIV §26: tech era → discovery fanfare id (4 characters; unknown era falls
  // back to the generic 'tech' sparkle). tech eras are ancient/renaissance/
  // industrial/modern (data/techs.json).
  const DISCOVERY_FANFARE = {
    ancient: 'discovery-ancient', renaissance: 'discovery-classical',
    industrial: 'discovery-industrial', modern: 'discovery-modern'
  };
  function discoveryFanfare(techId) {
    const t = ctx.session && ctx.session.ruleset && ctx.session.ruleset.techs
      ? ctx.session.ruleset.techs[techId] : null;
    return (t && DISCOVERY_FANFARE[t.era]) || 'tech';
  }

  // --- cue wiring: fog-filtered events → cues -------------------------------
  // (session-optional: the setup screen and the soundboard use tunes-only)
  const cityOwner = (state) => (cid) => (state.cities[cid] ? state.cities[cid].owner : null);
  if (ctx.session && ctx.session.onChange) {
    ctx.session.onChange((state, events) => {
      if (!events || events.length === 0) return;
      // fog gate: only sound what the viewer could actually witness (same as
      // the turn log) — session round events are omniscient
      const seen = filterEvents(state, events, ctx.HUMAN);
      const owner = cityOwner(state);
      for (const e of seen) {
        let id = soundForEvent(e, ctx.HUMAN, owner);
        // XIV §26: a viewer's OWN discovery earns the era-specific celebration
        // fanfare (sound-map stays pure/ruleset-free, so the era lookup — which
        // needs the ruleset — happens here).
        if (id === 'tech' && e.type === 'techDiscovered') id = discoveryFanfare(e.tech);
        if (id) play(id);
      }
    });
  }

  return { play, playTune, stopTune, get cuesPlayed() { return played; } };
}
